services:
  cine-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_API_KEY=AIzaSyCukj0-d2-dG44wWF78tWH9CoTgGkZpsVM
      - GEMINI_API_VERSION=v1
    volumes:
      - .:/app  # Esto permite que si cambias el código, se vea en el contenedor
    restart: always